package com.financial.view;

import java.awt.Container;
import java.awt.event.ActionEvent;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JTextField;

import com.financial.account.Account;
import com.financial.customers.Address;
import com.financial.customers.Person;
import com.financial.factories.IFinancialFactory;
import com.financial.interfaces.IAccount;
import com.financial.utilities.CommonResources;

public class Dialog_AddAccount extends JDialog {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	protected AbstractFrm parent;
	protected IAccount account;
	protected IFinancialFactory financialFactory;
	
	public Dialog_AddAccount(String title, AbstractFrm parent,  IFinancialFactory financialFactory) {
		super(parent);

		this.financialFactory = financialFactory;
		this.parent = parent;

		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		// {{INIT_CONTROLS
		setTitle("Add compamy account");
		setModal(true);
		getContentPane().setLayout(null);
		setSize(298, 339);
		setVisible(false);
		
		addFields(getContentPane());
//		JRadioButton_Chk.setText("Checkings");
//		JRadioButton_Chk.setActionCommand("Checkings");
//		getContentPane().add(JRadioButton_Chk);
//		JRadioButton_Chk.setBounds(36, 12, 84, 24);
//		JRadioButton_Sav.setText("Savings");
//		JRadioButton_Sav.setActionCommand("Savings");
//		getContentPane().add(JRadioButton_Sav);
//		JRadioButton_Sav.setBounds(36, 36, 84, 24);
		

	}
	
	public IAccount getAccount(){
		return this.account;
	}

	public void addFields(Container container){
		JLabel1.setText("Name");
		getContentPane().add(JLabel1);
		JLabel1.setForeground(java.awt.Color.black);
		JLabel1.setBounds(12, 96, 48, 24);
		JLabel2.setText("Street");
		getContentPane().add(JLabel2);
		JLabel2.setForeground(java.awt.Color.black);
		JLabel2.setBounds(12, 120, 48, 24);
		JLabel3.setText("City");
		getContentPane().add(JLabel3);
		JLabel3.setForeground(java.awt.Color.black);
		JLabel3.setBounds(12, 144, 48, 24);
		JLabel4.setText("State");
		getContentPane().add(JLabel4);
		JLabel4.setForeground(java.awt.Color.black);
		JLabel4.setBounds(12, 168, 48, 24);
		JLabel5.setText("Zip");
		getContentPane().add(JLabel5);
		JLabel5.setForeground(java.awt.Color.black);
		JLabel5.setBounds(12, 192, 48, 24);
//		JLabel6.setText("No of employees");
//		getContentPane().add(JLabel6);
//		JLabel6.setForeground(java.awt.Color.black);
//		JLabel6.setBounds(12, 216, 96, 24);
		JLabel7.setText("Email");
		getContentPane().add(JLabel7);
		JLabel7.setForeground(java.awt.Color.black);
		JLabel7.setBounds(12, 240, 48, 24);
		getContentPane().add(txtName);
		txtName.setBounds(120, 96, 156, 20);
		getContentPane().add(txtCity);
		txtCity.setBounds(120, 144, 156, 20);
		getContentPane().add(txtState);
		txtState.setBounds(120, 168, 156, 20);
		getContentPane().add(txtStreet);
		txtStreet.setBounds(120, 120, 156, 20);
		getContentPane().add(txtZip);
		txtZip.setBounds(120, 192, 156, 20);
//		getContentPane().add(JTextField_NoOfEmp);
//		JTextField_NoOfEmp.setBounds(120, 216, 156, 20);
		getContentPane().add(txtEmail);
		txtEmail.setBounds(120, 240, 156, 20);
		JButton_OK.setText("OK");
		JButton_OK.setActionCommand("OK");
		getContentPane().add(JButton_OK);
		JButton_OK.setBounds(48, 276, 84, 24);
		JButton_Calcel.setText("Cancel");
		JButton_Calcel.setActionCommand("Cancel");
		getContentPane().add(JButton_Calcel);
		JButton_Calcel.setBounds(156, 276, 84, 24);
//		JLabel8.setText("Acc Nr");
//		getContentPane().add(JLabel8);
//		JLabel8.setForeground(java.awt.Color.black);
//		JLabel8.setBounds(12, 72, 48, 24);
//		getContentPane().add(JTextField_ACNR);
//		
//		JTextField_ACNR.setBounds(120, 72, 156, 20);
		// }}

		// {{REGISTER_LISTENERS
		SymAction lSymAction = new SymAction();
		JButton_OK.addActionListener(lSymAction);
		JButton_Calcel.addActionListener(lSymAction);
	}

	class SymAction implements java.awt.event.ActionListener {
		public void actionPerformed(java.awt.event.ActionEvent event) {
			Object object = event.getSource();
			if (object == JButton_OK)
				buttonOK_actionPerformed(event);
			else if (object == JButton_Calcel)
				buttonCancel_actionPerformed(event);
		}
	}
	
	
	public void doFurtherWorks(){
		Person person = new Person();
		account = financialFactory.createAccount(CommonResources.ACCOUNT_TYPE_DEFAULT);
		account.setAccountHolder(person);
		account.getAccountHolder().setName(txtName.getText());
		Address address = new Address(txtStreet.getText(), txtCity.getText(), txtCity.getText(), Integer.parseInt(txtZip.getText()));
		account.getAccountHolder().setAddress(address);
	}

	void buttonOK_actionPerformed(java.awt.event.ActionEvent event) {
		// parentframe.accountnr=JTextField_ACNR.getText();
		// parentframe.clientName=JTextField_NAME.getText();
		// parentframe.street=JTextField_STR.getText();
		// parentframe.city=JTextField_CT.getText();
		// parentframe.zip=JTextField_ZIP.getText();
		// parentframe.state=JTextField_ST.getText();
		// if (JRadioButton_Chk.isSelected())
		// parentframe.accountType="Ch";
		// else
		// parentframe.accountType="S";
		// parentframe.newaccount=true;
		
		doFurtherWorks();
		dispose();

	}

	void buttonCancel_actionPerformed(java.awt.event.ActionEvent event) {
		dispose();

	}

//	JRadioButton JRadioButton_Chk = new JRadioButton();
//	JRadioButton JRadioButton_Sav = new JRadioButton();
	JLabel JLabel1 = new JLabel();
	JLabel JLabel2 = new JLabel();
	JLabel JLabel3 = new JLabel();
	JLabel JLabel4 = new JLabel();
	JLabel JLabel5 = new JLabel();
//	JLabel JLabel6 = new JLabel();
	JLabel JLabel7 = new JLabel();
	protected JTextField txtName = new JTextField();
	protected JTextField txtCity = new JTextField();
	protected JTextField txtState = new JTextField();
	protected JTextField txtStreet = new JTextField();
	protected JTextField txtZip = new JTextField();
//	JTextField JTextField_NoOfEmp = new JTextField();
	protected JTextField txtEmail = new JTextField();
	protected JButton JButton_OK = new JButton();
	protected JButton JButton_Calcel = new JButton();
//	JLabel JLabel8 = new JLabel();
//	JTextField JTextField_ACNR = new JTextField();

}
